# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'olist_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'olist_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  olist_analytics:
    # Configuration for staging models
    staging:
      +materialized: table

# Global variables you can use across your project
vars:
  # Date variables for incremental models
  start_date: '2016-01-01'
  end_date: '2018-12-31'
  
  # Business logic variables
  on_time_delivery_threshold_days: 30
  high_value_order_threshold: 200

# Test configurations
tests:
  +store_failures: true